### ISSUE TITLE
error: pathspec 'REPR_106_pseudo.py' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by shipleyxie** [see--/speech_recognition#1]
i git clone your project , and then 
**1、mkdir data 
2、ln -s /home/data/test   data/test
3、ln -s /home/data/train data/train
4、 git checkout 6892d80**
Note: checking out '6892d80'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 6892d80... Training 106: Time sliced with attention
**5、 git checkout master REPR_106_pseudo.py submission_091_leftloud_tta_all_labels.csv submission_096_leftloud_tta_all_labels.csv submission_098_leftloud_tta_all_labels.csv**

error: pathspec 'REPR_106_pseudo.py' did not match any file(s) known to git.

——————————————————————————————————
and i got this error ,could U please tell me how to fix it??

**Comment by see--** [comment]
You are right, thanks. I just uploaded the file. I should add that I can't test it right now, as I don't have the dataset here. Let me know if it helps.

**Comment by shipleyxie** [comment]
problem solved , now ready to run  ~
